[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; Serial Monitor settings (to see the text output)
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0

; Upload settings
upload_speed = 115200 ; Slower speed is safer for these boards
upload_port = COM9    ; We explicitly tell it to use your new port!

; Libraries we need
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    madhephaestus/ESP32Servo @ ^3.0.5  ; <--- NEW LINE